- id: buiten_id
  alias: Buitenlichten aan
  trigger:
    platform: sun
    event: sunset
    offset: '+00:30:00'
  action:
  - service: switch.turn_on
    entity_id:
    - group.buiten
- id: buiten_uit_id
  alias: Buitenlichten uit
  trigger:
  - platform: time
    at: '23:00'
  action:
  - service: switch.turn_off
    entity_id:
    - group.buiten

- id: terras_id
  alias: Terras licht
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_3
      from: 'off'
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id:
          - switch.terras_lamp_buiten

- id: terras_id_uit
  alias: Terras uit
  trigger:
    - platform: state
      entity_id: binary_sensor.presence_3
      from: 'on'
      to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.terras_lamp_buiten

- id: timer_id
  alias: Turn off hallway lights 10 minutes after trigger
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.terras
  action:
    - service: switch.turn_off
      data:
        entity_id:
          - switch.terras_lamp_buiten
